// Generated by CoffeeScript 1.6.3
exports.config = {
  files: {
    javascripts: {
      defaultExtension: 'coffee',
      joinTo: {
        'scripts/app.js': /^app/,
        'scripts/vendor.js': /^vendor/
      },
      order: {
        before: ['vendor/scripts/console-helper.js', 'vendor/scripts/jquery.js', 'vendor/scripts/underscore.js', 'vendor/scripts/backbone.js']
      }
    },
    stylesheets: {
      joinTo: 'styles/app.css',
      order: {
        before: ['app/styles/main.css']
      }
    },
    templates: {
      joinTo: 'scripts/app.js'
    }
  }
};
