// Generated by CoffeeScript 1.6.3
var HomeView, NewTodoView, Router, StatsView, TodoView, Todos, TodosView, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Todos = require('models/todos');

HomeView = require('views/home_view');

NewTodoView = require('views/new_todo_view');

StatsView = require('views/stats_view');

TodoView = require('views/todo_view');

TodosView = require('views/todos_view');

module.exports = Router = (function(_super) {
  __extends(Router, _super);

  function Router() {
    _ref = Router.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Router.prototype.routes = {
    '': 'home'
  };

  Router.prototype.initialize = function() {
    this.todos = new Todos;
    this.homeView = new HomeView();
    this.statsView = new StatsView({
      collection: this.todos
    });
    this.newTodoView = new NewTodoView({
      collection: this.todos
    });
    return this.todosView = new TodosView({
      collection: this.todos
    });
  };

  Router.prototype.home = function() {
    return this.todos.fetch();
  };

  return Router;

})(Backbone.Router);
