// Generated by CoffeeScript 1.6.3
var Application;

Application = {
  initialize: function() {
    var HomeView, NewTodoView, Router, StatsView, TodoView, Todos, TodosView;
    Todos = require('models/todos');
    Router = require('routers/router');
    HomeView = require('views/home_view');
    NewTodoView = require('views/new_todo_view');
    StatsView = require('views/stats_view');
    TodoView = require('views/todo_view');
    TodosView = require('views/todos_view');
    this.todos = new Todos();
    this.homeView = new HomeView();
    this.statsView = new StatsView();
    this.newTodoView = new NewTodoView();
    this.todosView = new TodosView();
    this.router = new Router();
    return typeof Object.freeze === "function" ? Object.freeze(Application) : void 0;
  }
};

module.exports = Application;
