// Generated by CoffeeScript 1.6.3
Handlebars.registerHelper('pluralize', function(count, fn) {
  // var pluralized, string;
  // string = fn();
  // pluralized = count === 1 ? string : "" + string + "s";
  // return new Handlebars.SafeString(pluralized);
});
