// Generated by CoffeeScript 1.6.3
var HomeView, View, application, template, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

View = require('./view');

application = require('application');

template = require('./templates/home');

module.exports = HomeView = (function(_super) {
  __extends(HomeView, _super);

  function HomeView() {
    _ref = HomeView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  HomeView.prototype.template = template;

  HomeView.prototype.el = '#home-view';

  HomeView.prototype.afterRender = function() {
    var $todo, viewName, _i, _len, _ref1, _results;
    $todo = this.$el.find('#app-wrapper');
    _ref1 = ['newTodo', 'todos', 'stats'];
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      viewName = _ref1[_i];
      _results.push($todo.append(application["" + viewName + "View"].render().el));
    }
    return _results;
  };

  return HomeView;

})(View);
