// Generated by CoffeeScript 1.6.3
var StatsView, View, application, template, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

View = require('./view');

application = require('application');

template = require('./templates/stats');

module.exports = StatsView = (function(_super) {
  __extends(StatsView, _super);

  function StatsView() {
    _ref = StatsView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  StatsView.prototype.template = template;

  StatsView.prototype.id = 'stats-view';

  StatsView.prototype.events = {
    'click .todo-clear': 'clearCompleted'
  };

  StatsView.prototype.getRenderData = function() {
    return {
      stats: {
        total: application.todos.length,
        done: application.todos.done().length,
        remaining: application.todos.remaining().length
      }
    };
  };

  StatsView.prototype.clearCompleted = function() {
    return application.todos.clearCompleted();
  };

  return StatsView;

})(View);
