// Generated by CoffeeScript 1.6.3
var TodoView, TodosView, View, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

View = require('./view');

TodoView = require('./todo_view');

module.exports = TodosView = (function(_super) {
  __extends(TodosView, _super);

  function TodosView() {
    this.render = __bind(this.render, this);
    this.addOne = __bind(this.addOne, this);
    _ref = TodosView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  TodosView.prototype.logging = true;

  TodosView.prototype.el = '#todos-view';

  TodosView.prototype.addOne = function(todo) {
    var view;
    view = new TodoView({
      model: todo
    });
    return this.$el.append(view.render().el);
  };

  TodosView.prototype.render = function() {
    return this.collection.each(this.addOne);
  };

  TodosView.prototype.initialize = function() {
    return this.listenTo(this.collection, 'sync', this.render);
  };

  return TodosView;

})(View);
