// Generated by CoffeeScript 1.6.3
var TodoView, TodosView, View, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

View = require('./view');

TodoView = require('./todo_view');

module.exports = TodosView = (function(_super) {
  __extends(TodosView, _super);

  function TodosView() {
    _ref = TodosView.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  TodosView.prototype.el = '#todos-view';

  TodosView.prototype.render = function() {
    var todo, view, _i, _len, _ref1, _results;
    console.log("test console log");
    console.log(this);
    this.$el.html('');
    _ref1 = this.collection.models;
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      todo = _ref1[_i];
      view = new TodoView({
        model: todo
      });
      _results.push(this.$el.append(view.render().el));
    }
    return _results;
  };

  TodosView.prototype.initialize = function() {
    return this.listenTo(this.collection, 'sync', this.render);
  };

  return TodosView;

})(View);
